volumes:
  heritage-nwa-volume:
    name: heritage-nwa-volume

services:
  db:
    image: postgres:17-bullseye
    volumes:
      - heritage-nwa-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 15432:5432

  api:
    environment:
      CORS_HOST: ${CORS_HOST}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_HOST: db:5432
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    user: "1000:1000"
    volumes:
      - ./api:/app

  client:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    user: "1000:1000"
    volumes:
      - ./client:/app
    environment:
      VITE_API_HOST: "http://localhost:8000"
      BASE_URL: "http://localhost:5173"
    ports:
      - "5173:5173"
